const express = require('express');
const helmet = require('helmet');
const rateLimit = require('express-rate-limit');
const cors = require('cors');
const hpp = require('hpp');
const xss = require('xss-clean');
const morgan = require('morgan');
const connectDb = require('./config/db');
const { port, corsOrigin } = require('./config/env');
require('./services/mqttService');
const app = express();
app.use(helmet());
app.use(rateLimit({ windowMs: 15*60*1000, max: 300 }));
app.use(cors({ origin: corsOrigin, credentials: true }));
app.use(express.json({ limit:'1mb' }));
app.use(hpp());
app.use(xss());
app.use(morgan('combined'));
app.use('/api/auth', require('./routes/authRoutes'));
app.use('/api/homes', require('./routes/homesRoutes'));
app.use('/api/devices', require('./routes/devicesRoutes'));
app.use('/api/automations', require('./routes/automationsRoutes'));
app.use('/api/payments', require('./routes/paymentsRoutes'));
app.use('/api/tickets', require('./routes/ticketsRoutes'));
app.get('/health', (_,res)=>res.json({status:'ok'}));
connectDb().then(()=>app.listen(port,()=>console.log(`API em ${port}`)));
